name: CI 

on:
  push:
    branches:
      - '**' # Trigger on all branches except main (due to branch protection)
  pull_request:
    branches:
      - main # Trigger on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13

    - name: Set GCC 13 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
        sudo update-alternatives --set gcc /usr/bin/gcc-13
        sudo update-alternatives --set g++ /usr/bin/g++-13

    - name: Verify GCC version
      run: |
        gcc --version
        g++ --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -S main

    - name: Build
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -S main

    - name: Build
      run: cmake --build build
    
    - name: unitary test
      run: |
        echo $(pwd)
        ./build/gd/crud

    - name: stress test
      run: |
        ./build/gd/greens
