name: CI 

on:
  push:
    branches:
      - '**' # Trigger on all branches except main (due to branch protection)
  pull_request:
    branches:
      - main # Trigger on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC 14
      uses: egor-tensin/setup-gcc@v1
      with:
        gcc-version: 14

    - name: Configure and Build
      run: |
        cmake --preset Release
        cmake --build build/release
    
    - name: Run Tests
      run: |
        ./build/release/main/gd/crud
        ./build/release/main/gd/greens -g 5 -b 10 -c 30 -o 50
